import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Loader from '../components/Loader'
import Nav from '../components/Nav'
import Results from '../components/Results'
import requests from '../utils/requests'


export default function Home({ results }) {
  // console.log(props);

  return (
    <div>
      <Head>
        <title>Hulu | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />
      {/* Navigation */}
      <Nav />
      {/* <Loader width='1920' /> */}
      {/* Results */}
      <Results results={results} /> 
    </div>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre; // firstly get - fetchHorror, fetchSciFi

  // make requests to their server based on genre
  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
                            .then(res => res.json());
  
  return {
    props: {
      results: request.results
    }
  }
}
